version: '3'

services:
###> doctrine/doctrine-bundle ###
  postgressql:
    image: postgres:15.1
    container_name: postgresql
    environment:
      # You should definitely change the password in production
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: root
    volumes:
      - ./postgres:/var/lib/postgresql/data:rw
    networks:
      - nginx-php8-mysql8-node
    ports:
      - "5432:5432"
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    container_name: mercure
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'symfony'
      MERCURE_SUBSCRIBER_JWT_KEY: 'symfony'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        anonymous
        cors_origins *
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    ports:
       - "80:80"
       - "443:443"
###< symfony/mercure-bundle ###
#docker run --name=mercure -e MERCURE_PUBLISHER_JWT_KEY='konshensx' -e MERCURE_SUBSCRIBER_JWT_KEY='konshensx' -p 80:80 -p 443:443 dunglas/mercure caddy run -config /etc/caddy/Caddyfile.dev
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
